apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: activemq
  name: activemq
  namespace: default
spec:
  ports:
  - name: activemq
    port: 61616
    targetPort: 61616
  - name: http
    port: 8161
    targetPort: console
  selector:
    app: activemq
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: activemq
  name: activemq
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: activemq
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: activemq
      labels:
        app: activemq
    spec:
      containers:
      - image: lie/activemq:5.15.10
        imagePullPolicy: "Always"
        name: activemq
        ports:
        - containerPort: 8161
          name: console
          protocol: TCP
        - containerPort: 61616
          protocol: TCP
        readinessProbe:
          periodSeconds: 10
          tcpSocket:
            port: 61616
          initialDelaySeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 61616
          initialDelaySeconds: 10
          timeoutSeconds: 3
