apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: api
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
      - image: lie/tomcat:7.0.96-jdk7-alpine
        imagePullPolicy: "Always"
        name: api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          #periodSeconds: 1
          httpGet:
            port: 8080
            path: /
          #initialDelaySeconds: 3
          #timeoutSeconds: 3
        livenessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 30
          timeoutSeconds: 30
