apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-master
  name: redis-master
  namespace: default
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-master
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-master
  name: redis-master
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-master
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: redis-master
      labels:
        app: redis-master
    spec:
      containers:
      - image: lie/redis-master:3.2.10
        imagePullPolicy: "Always"
        name: redis-master
        ports:
        - containerPort: 6379
          protocol: TCP
        #readinessProbe:
          #periodSeconds: 10
          #tcpSocket:
            #port: 6379
          #initialDelaySeconds: 30
          #timeoutSeconds: 30
        #livenessProbe:
          #tcpSocket:
            #port: 6379
          #initialDelaySeconds: 30
          #timeoutSeconds: 30
