apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-sentinel
  name: redis-sentinel
  namespace: default
spec:
  ports:
  - port: 26379
    targetPort: 26379
  selector:
    app: redis-sentinel
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-sentinel
  name: redis-sentinel
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-sentinel
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: redis-sentinel
      labels:
        app: redis-sentinel
    spec:
      containers:
      - image: lie/redis-sentinel:3.2.10
        imagePullPolicy: "Always"
        name: redis-sentinel
        ports:
        - containerPort: 26379
          protocol: TCP
        #readinessProbe:
        #  periodSeconds: 1
        #  tcpSocket:
        #    port: 6379
        #livenessProbe:
        #  tcpSocket:
        #    port: 6379
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 30
