apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-slave
  name: redis-slave
  namespace: default
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-slave
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-slave
  name: redis-slave
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-slave
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: redis-slave
      labels:
        app: redis-slave
    spec:
      containers:
      - image: lie/redis-slave:3.2.10
        imagePullPolicy: "Always"
        name: redis-slave
        ports:
        - containerPort: 6379
          protocol: TCP
        #readinessProbe:
        #  periodSeconds: 1
        #  tcpSocket:
        #    port: 6379
        #livenessProbe:
        #  tcpSocket:
        #    port: 6379
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 30
